### ISSUE TITLE
Unable to access SMB in directory channels

### ISSUE THREAD

**Issue by InaudibleDirge** [Steveb1968/script.pseudotv#22]
I'm unable to access SMB when using directory channels. I have those folders on the same network server that all of the other videos are located, but they are not loaded into the Kodi library as they are bumps, commercials, etc.

Just wondering if this is intended or something else.

**Comment by Steveb1968** [comment]
Known bug. workaround would be use a local dir until I get around to fixing it.

**Comment by rafaelvieiras** [comment]
When I try to share my channels with samba, I receive this:

```
2019-11-16 10:30:56.977 T:140609637574400   ERROR: Rename - Error( No such file or directory )
2019-11-16 10:30:56.977 T:140609637574400   ERROR: Rename - Error renaming file smb://NASHOME/media/Kodi/PseudoTv/cache/FileLock.dat
2019-11-16 10:30:57.479 T:140609637574400   ERROR: Rename - Error( No such file or directory )
2019-11-16 10:30:57.479 T:140609637574400   ERROR: Rename - Error renaming file smb://NASHOME/media/Kodi/PseudoTv/cache/FileLock.dat
2019-11-16 10:30:57.982 T:140609637574400   ERROR: Rename - Error( No such file or directory )
2019-11-16 10:30:57.982 T:140609637574400   ERROR: Rename - Error renaming file smb://NASHOME/media/Kodi/PseudoTv/cache/FileLock.dat
2019-11-16 10:30:58.483 T:140609637574400   ERROR: Rename - Error( No such file or directory )
2019-11-16 10:30:58.483 T:140609637574400   ERROR: Rename - Error renaming file smb://NASHOME/media/Kodi/PseudoTv/cache/FileLock.dat
2019-11-16 10:30:58.986 T:140609637574400   ERROR: Rename - Error( No such file or directory )
2019-11-16 10:30:58.986 T:140609637574400   ERROR: Rename - Error renaming file smb://NASHOME/media/Kodi/PseudoTv/cache/FileLock.dat
2019-11-16 10:30:59.486 T:140609637574400 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://NASHOME/media/Kodi/PseudoTv/cache/44516.lock
2019-11-16 10:30:59.594 T:140609637574400 WARNING: Previous line repeats 1 times.
2019-11-16 10:30:59.594 T:140609637574400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'TVOverlay' object has no attribute 'sleepTimeValue'
                                            Traceback (most recent call last):
                                              File "/home/rafael/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 686, in onAction
                                                self.startSleepTimer()
                                              File "/home/rafael/.kodi/addons/script.pseudotv/resources/lib/Overlay.py", line 792, in startSleepTimer
                                                if self.sleepTimeValue == 0:
                                            AttributeError: 'TVOverlay' object has no attribute 'sleepTimeValue'
                                            -->End of Python script error report<--
2019-11-16 10:31:02.339 T:140609629181696 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://NASHOME/media/Kodi/PseudoTv/cache/13259.lock
```

Client: Ubuntu 19.04 with SMBv1 forcede on kodi
Server: Ubuntu Serve 18.10 with OMV

**Comment by rafaelvieiras** [comment]
@Steveb1968
On Overlay.py, I add `self.sleepTimeValue = 0` to `def __init__()` of `class TVOverlay(xbmcgui.WindowXMLDialog)`. After this, I can be use settings over samba.

It's ok? It's a goodie pratice?

**Comment by Steveb1968** [comment]
Yea mate that's all good, it's the default anyway.
I can add that if you like, plus I'll clean up that setting.

**Comment by rafaelvieiras** [comment]
I can add that in my next PR! :smile: 

I think about a roadmap or a TODO.md file, for list things to fix basic bugs and steps to prepare add-on for kodi oficial repository.

**Comment by Steveb1968** [comment]
Just a txt file is good enough for me. :) And this addon will never be in the Kodi repo!

**Comment by rafaelvieiras** [comment]
Ok!
:open_mouth: Why never? This is a perfect addon for this! Not use piracy! Is simple to use!

**Comment by Steveb1968** [comment]
The Kodi Repo is Lunatixz's puppy! This is one of my hobbies.. :) I just can't let this addon stop working! :)

**Comment by Technobob** [comment]
A workaround for this is to map your network shares
If you're using Libreelec here is how to do it and in Windows right click your shares and select map drive and assign a drive letter.
https://libreelec.wiki/how_to/mount_network_share
