### ISSUE TITLE
Interleave Issue

### ISSUE THREAD

**Issue by gils001** [Steveb1968/script.pseudotv#57]
Added an Interleave rule to channel 1 for channel 25 (Directory Channel). PseudoTV stops upon initialization while updating channels. This is not an issue in the 'Leia' Branch which is 20 commits behind.

> 2020-04-17 15:57:34.330 T:6176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'int' objects
                                            Traceback (most recent call last):
                                              File "C:\Users\gilra\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\Overlay.py", line 182, in onInit
                                                if self.readConfig() == False:
                                              File "C:\Users\gilra\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\Overlay.py", line 264, in readConfig
                                                self.channels = self.channelList.setupList()
                                              File "C:\Users\gilra\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\ChannelList.py", line 108, in setupList
                                                self.setupChannel(i + 1, False, makenewlists, False)
                                              File "C:\Users\gilra\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\ChannelList.py", line 284, in setupChannel
                                                if self.makeChannelList(channel, chtype, chsetting1, chsetting2, append) == True:
                                              File "C:\Users\gilra\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\ChannelList.py", line 508, in makeChannelList
                                                fileList = self.runActions(RULES_ACTION_LIST, channel, fileList)
                                              File "C:\Users\gilra\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\ChannelList.py", line 1183, in runActions
                                                parameter = rule.runAction(action, self, parameter)
                                              File "C:\Users\gilra\AppData\Roaming\Kodi\addons\script.pseudotv\resources\lib\Rules.py", line 1027, in runAction
                                                newstr += "//" + channelList.channels[chan - 1].getItemPlaycount(startingep - 1)
                                            TypeError: cannot concatenate 'str' and 'int' objects
                                            -->End of Python script error report<--

**Comment by fnord12** [comment]
This should be addressed with the latest commit.  I hadn't tested the possibility of interleaving a directory channel and wasn't accounting for the possibility of a no playcount value being treated as an integer.  Sorry for the inconvenience.  Let me know if it's fixed.  (I was able to replicate on my end and it is now fixed for me.)

**Comment by gils001** [comment]
> This should be addressed with the latest commit. I hadn't tested the possibility of interleaving a directory channel and wasn't accounting for the possibility of a no playcount value being treated as an integer. Sorry for the inconvenience. Let me know if it's fixed. (I was able to replicate on my end and it is now fixed for me.)

All good on my end with the new commit.. Thanks for the fix! I may add a couple minor issues down the line.
